add_subdirectory(time)
add_subdirectory(cli)
add_subdirectory(i18n)
add_subdirectory(log)
add_subdirectory(event)
add_subdirectory(engine)
add_subdirectory(simulation)
add_subdirectory(replay)
add_subdirectory(ecs)
add_subdirectory(ecs_commons)
add_subdirectory(scheduler)
add_subdirectory(rng)
add_subdirectory(wfc)
add_subdirectory(animation)
add_subdirectory(pathfinding)
add_subdirectory(gfx)
add_subdirectory(ttf)
add_subdirectory(ui)
add_subdirectory(input)
add_subdirectory(sound)
add_subdirectory(holdem)
add_subdirectory(app)
