add_subdirectory(time)
add_subdirectory(log)
add_subdirectory(event)
add_subdirectory(engine)
add_subdirectory(replay)
add_subdirectory(ecs)
add_subdirectory(reducer)
add_subdirectory(scheduler)
add_subdirectory(wfc)
add_subdirectory(pathfinding)
add_subdirectory(gfx)
add_subdirectory(ui)
add_subdirectory(input)
add_subdirectory(holdem)
add_subdirectory(app)
