name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    outputs:
      version: ${{ steps.version.outputs.version }}

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --no-save \
            semantic-release@25.0.8 \
            @semantic-release/changelog@7.0.0 \
            @semantic-release/git@11.0.1
          npx semantic-release
      - name: Fetch tags
        run: git fetch --tags
      - name: Get released version
        id: version
        run: |
          if ! VERSION=$(git describe --tags --abbrev=0 --match "v*"); then
            echo "No release created"
            exit 1
          fi
          VERSION=${VERSION#v}
          echo "Released version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  build:
    name: Build
    needs: release
    uses: ./.github/workflows/build.yml
    permissions:
      contents: write
      packages: write
    with:
      version: ${{ needs.release.outputs.version }}
      latest: true
      ref: v${{ needs.release.outputs.version }}
