#pragma once

#include <cstddef>

#include <antwika/event/ITickEventSink.hpp>
#include <antwika/event/TickEvent.hpp>
#include <antwika/time/Tick.hpp>
#include <antwika/ui/Interactions.hpp>
#include <antwika/ui/Pointer.hpp>
#include <antwika/ui/WidgetId.hpp>

#include "antwika/game/Camera.hpp"
#include "antwika/game/CityRatings.hpp"
#include "antwika/game/GameState.hpp"
#include "antwika/game/IMenuCommands.hpp"
#include "antwika/game/MapView.hpp"
#include "antwika/game/InputFold.hpp"
#include "antwika/game/MenuModalScene.hpp"
#include "antwika/game/PauseState.hpp"
#include "antwika/game/RoadDrag.hpp"
#include "antwika/game/Toolbar.hpp"
#include "antwika/game/UiOverlay.hpp"
#include "antwika/game/ViewCommands.hpp"

namespace antwika::game
{

    using antwika::event::ITickEventSink;
    using antwika::event::TickEvent;
    using antwika::ui::Interactions;
    using antwika::ui::Pointer;
    using antwika::ui::WidgetId;

    /**
     * @brief Turns this tick's input into toolbar presses, and the
     * toolbar into a picture for the renderer.
     *
     * **Describing and resolving the UI happens here, downstream of the
     * recorder, on purpose.** A replay carries the click and works out
     * which button it hit all over again; this app therefore defines no
     * event for a button at all, and no `ui.*` name is ever persisted.
     * Persisting the press *and* what it activated would zoom twice for
     * one click, the same trap GridSink describes for placing a tile.
     *
     * Registered before GridSink, so a press has been resolved against
     * the toolbar by the time the grid sees it, and UiOverlay can answer
     * whether the click was the toolbar's. On engine.tick it describes
     * one last time, so what the renderer paints in that tick is the
     * picture of the state the tick ends with.
     *
     * The canvas comes off the overlay, which is the size the window
     * was asked for rather than the size one reports -- see UiOverlay.
     *
     * The pause button is the same rule read out loud: pressing it
     * toggles PauseState here, in the tick path, so a replay pauses on
     * precisely the ticks the live run paused on. Nothing about a pause
     * is persisted, and no `game.pause` event exists to persist.
     *
     * What the pointer is doing comes from the shared InputFold, which
     * is registered ahead of this sink and holds the app's one answer --
     * regenerated from the same events on replay, so it needs no
     * recording of its own.
     *
     * **The menu modal is this sink's too, and it is simulation state**
     * in exactly the sense PauseState, the camera and the selected tool
     * are: whether it is up decides what a recorded press *means*, so it
     * is regenerated from the recorded clicks that opened and
     * closed it rather than recorded itself. No `game.*` or `ui.*` event exists
     * for opening, closing or leaving by it. It lives here rather than
     * in a shared state object because this sink is the only thing that
     * reads it: what it covers is reported through UiOverlay like
     * everything else the UI covers, and what it draws is appended to
     * the same picture the bar goes into.
     *
     * **The top bar's game menu is simulation state on exactly those
     * terms**, and it is the clearer case of the two: an open list sits
     * over the city, so whether it is open decides whether a click at a
     * pixel chooses "load game" or lays a road. It is therefore held
     * here, written inside the tick path, and regenerated by a replay
     * from the click that dropped it -- antwika::ui keeps no such flag
     * of its own, deliberately, for this very reason.
     *
     * **A press that lands anywhere but the list puts it away, and that
     * press does nothing else at all.** It is reported as the UI's, so
     * GridSink's existing rule keeps it off the city; a press that both
     * dismissed a menu and laid a tile under it would be one click doing
     * two things nobody asked for. Pressing the closed box again is the
     * exception, since that is what closing it deliberately looks like.
     *
     * What an item *does* is IMenuCommands' rather than this sink's, so
     * that a list's layout and the transitions behind it are asserted
     * apart -- and so that leaving for the main menu is one piece of
     * code whether the modal or the menu asked for it.
     *
     * Three rules about the modal are worth stating outright.
     *
     * **A press is resolved against the modal alone while it is up**, so
     * a toolbar button cannot be pressed through it, and the modal's
     * commands are appended after the bar's so paint order puts it in
     * front -- which is how "on top" is said where antwika::gfx offers
     * no depth. The scrim's fill is what makes UiOverlay report the
     * pointer as covered wherever it is, so GridSink's existing rule
     * keeps the press off the city with no second mechanism.
     *
     * **Opening the modal ends a road drag in progress, and that drag
     * lays nothing at all.** What a drag lays is what its release said,
     * and a release arriving over the modal never said it; leaving the
     * gesture alive would also leave a route being planned against a
     * city nobody can see.
     *
     * **Opening the modal holds nothing**, and neither does entering a
     * city: a run progresses all the time unless a player has asked for
     * a pause, so the city goes on behind the modal exactly as it goes
     * on behind the world map. The pause button is the only thing that
     * writes PauseState, and it writes the state it was showing the
     * opposite of rather than flipping one -- see PauseState for why an
     * absolute value is what more than one player asking needs.
     */
    class UiSink final : public ITickEventSink
    {
    public:
        /**
         * @brief Construct the sink over everything it drives.
         * @param camera Read to describe the bar's zoom readout; the
         * buttons move it through viewCommands rather than from here.
         * Must outlive this sink.
         * @param overlay Written every tick. Must outlive this sink.
         * @param input The folded input, holding the event being
         * handled. Must outlive this sink, and must be registered ahead
         * of it.
         * @param toolbar Describes the bar. Must outlive this sink.
         * @param pause Read to label the pause button; the button
         * holds and releases the run through viewCommands rather than
         * from here. Must outlive this sink.
         * @param view Which picture of the city the overlay dropdown
         * has chosen. Written here and by nothing else, inside the tick
         * path, so a replay chooses the same one. Must outlive this
         * sink.
         * @param commands What the game menu's items and the modal's
         * main-menu item ask for. Must outlive this sink.
         * @param drag The road drag opening the modal ends. Written here
         * and by GridSink, and by nothing else. Must outlive this sink.
         * @param modal Describes the menu modal. Must outlive this sink.
         * @param viewCommands What the bar's first four buttons ask
         * for -- the same four verbs a bound key asks for, which is why
         * neither sink spells them out any more. Must outlive this
         * sink.
         * @param ratings How the city is doing, reported by the
         * last two readouts on the bottom bar. Written by RatingsSystem
         * in the observe phase, so it shows the city as the tick left it
         * -- which a replay reaches identically, since every input this
         * sink is given arrives before the scheduler runs. Must outlive
         * this sink.
         * @param state The plain app state whose bank the bar reports,
         * beside the ratings. Spent by GridSink from the clicks a
         * recording holds, so a replay draws the same number. Must
         * outlive this sink.
         */
        UiSink(
            const Camera &camera,
            UiOverlay &overlay,
            const InputFold &input,
            const Toolbar &toolbar,
            const PauseState &pause,
            MapViewState &view,
            IMenuCommands &commands,
            RoadDrag &drag,
            const MenuModalScene &modal,
            ViewCommands &viewCommands,
            const CityRatings &ratings,
            const GameState &state);

        UiSink(const UiSink &) = delete;
        UiSink(UiSink &&) = delete;

        UiSink &operator=(const UiSink &) = delete;
        UiSink &operator=(UiSink &&) = delete;

        /**
         * @brief Apply a tick event.
         * @param event An input.* event is resolved against the toolbar
         * and acted on; engine.tick describes the bar once more for the
         * renderer; anything else is ignored.
         */
        void handle(const TickEvent &event) override;

        /**
         * @brief Check whether the menu modal is up.
         * @return True between opening it and closing it.
         */
        [[nodiscard]] bool menuOpen() const noexcept;

        /**
         * @brief Check whether the top bar's game menu is dropped down.
         * @return True between the press that opened it and the one that
         * put it away.
         */
        [[nodiscard]] bool gameMenuOpen() const noexcept;

        /**
         * @brief Check whether the top bar's overlay menu is dropped
         *        down.
         * @return True between the press that opened it and the one that
         * put it away.
         */
        [[nodiscard]] bool viewMenuOpen() const noexcept;

    private:
        [[nodiscard]] Pointer pointerNow(bool pressed) const;

        [[nodiscard]] Frame describeNow(bool pressed) const;

        void refreshAndAct(bool pressed);

        [[nodiscard]] bool actOnUi(
            const Interactions &interactions, bool pressed);

        void actOnBar(WidgetId activated);

        void actOnModal(WidgetId activated);

        void chooseFrom(std::size_t index);

        void chooseView(std::size_t index);

        void openModal();

        void selectFrom(WidgetId activated);

        const Camera &camera;
        UiOverlay &overlay;
        const InputFold &input;
        const Toolbar &toolbar;
        const PauseState &pause;
        MapViewState &view;
        IMenuCommands &commands;
        RoadDrag &drag;
        const MenuModalScene &modal;
        ViewCommands &viewCommands;
        const CityRatings &ratings;
        const GameState &state;

        // Whether the menu modal is up, which is simulation state.
        // Written here, inside the tick path, and read nowhere else.
        // A replay regenerates it from the clicks the file holds.
        bool modalOpen = false;

        // Whether the game menu's list is showing, on the same terms.
        // antwika::ui holds no such flag, deliberately.
        // See ui::DropdownSpec: this is the one place it lives.
        bool listOpen = false;

        // And whether the overlay menu's is, on those terms again.
        // Two lists, so two flags rather than one.
        // One may be open while the other is not.
        // A shared flag would open both at once.
        bool viewOpen = false;

        // The tick the bar reports, off the event being handled.
        // Every tick event carries the tick it belongs to.
        // So this is the simulation's count rather than a second one.
        // A replay hands over the same numbers in the same order.
        antwika::time::Tick tick = 0;
    };

} // namespace antwika::game
